/**
 * EventCode - unique identifiers enum for stimulus internal events
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * * * * * * NAME CONVENTION [ <VERB>_<SUBJECT>_<SECONDARY_SUBJECT> ] NAME CONVENTION  * * * * * * * * * * * * *
 * * * VERB: should describe current action. e.g. ADD | REMOVE | UPDATE | CANCEL
 * * * SUBJECT: the main actor of current action. This should be equal with entityType property from event object
 * * * @see .EventCategoryType for selecting the right one
 * * * SECONDARY_SUBJECT <optional> : should describe what is inside meta json field @see ./event.entity.ts/.EventMeta
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 */
export enum EventCode {
  ADD_COMPANY_TO_PROJECT = 'ADD_COMPANY_TO_PROJECT',
  REMOVE_COMPANY_FROM_PROJECT = 'REMOVE_COMPANY_FROM_PROJECT',
  ANSWER_PROJECT_COMPANY_CRITERIA = 'ANSWER_PROJECT_COMPANY_CRITERIA',
  UPDATE_PROJECT_STATUS = 'UPDATE_PROJECT_STATUS',
  UPDATE_PROJECT_COMPANIES = 'UPDATE_PROJECT_COMPANIES',
  UPDATE_PROJECT_INFO = 'UPDATE_PROJECT_INFO',
  ADD_PROJECT_COLLABORATORS = 'ADD_PROJECT_COLLABORATORS',
  RESPONSE_PROJECT_COLLABORATORS = 'RESPONSE_PROJECT_COLLABORATORS',
  EVALUATE_PROJECT_COMPANY = 'EVALUATE_PROJECT_COMPANY',
  UPDATE_COMPANY_EVALUATION = 'UPDATE_COMPANY_EVALUATION',
  CREATE_PROJECT = 'CREATE_PROJECT',
  CANCEL_PROJECT = 'CANCEL_PROJECT',
  ARCHIVE_PROJECT = 'ARCHIVE_PROJECT',
  PAUSE_PROJECT = 'PAUSE_PROJECT',
  CREATE_COMPANY = 'CREATE_COMPANY',
  UPDATE_COMPANY_SETTINGS = 'UPDATE_COMPANY_SETTINGS',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  CREATE_COMPANY_INSURANCE = 'CREATE_COMPANY_INSURANCE',
  UPDATE_COMPANY_INSURANCE = 'UPDATE_COMPANY_INSURANCE',
  CREATE_COMPANY_CERTIFICATION = 'CREATE_COMPANY_CERTIFICATION',
  UPDATE_COMPANY_CERTIFICATION = 'UPDATE_COMPANY_CERTIFICATION',
  CREATE_COMPANY_PRODUCT = 'CREATE_COMPANY_PRODUCT',
  UPDATE_COMPANY_PRODUCT = 'UPDATE_COMPANY_PRODUCT',
  CREATE_COMPANY_LOCATION = 'CREATE_COMPANY_LOCATION',
  UPDATE_COMPANY_LOCATION = 'UPDATE_COMPANY_LOCATION',
  CREATE_COMPANY_CONTACT = 'CREATE_COMPANY_CONTACT',
  UPDATE_COMPANY_CONTACT = 'UPDATE_COMPANY_CONTACT',
  CREATE_COMPANY_CONTINGENCY = 'CREATE_COMPANY_CONTINGENCY',
  UPDATE_COMPANY_CONTINGENCY = 'UPDATE_COMPANY_CONTINGENCY',
  UPDATE_COMPANY_STATUS = 'UPDATE_COMPANY_STATUS',
  UPDATE_COMPANY_TYPE = 'UPDATE_COMPANY_TYPE',
  REMOVE_FROM_COMPANY_LIST = 'REMOVE_FROM_COMPANY_LIST',
  ADD_TO_COMPANY_LIST = 'ADD_TO_COMPANY_LIST',
  SHARED_LIST = 'SHARED_LIST',
  SHARED_LIST_CHANGE_STATUS = 'SHARED_LIST_CHANGE_STATUS',
  SET_SUPPLIER_TIER_COMPANY = 'SET_SUPPLIER_TIER_COMPANY',
}

export enum EventCategoryType {
  COMPANY = 'COMPANY',
  PROJECT = 'PROJECT',
  DEPARTMENT = 'DEPARTMENT',
  LIST = 'LIST',
}

export enum EventLevel {
  INFO = 'INFO',
  WARNING = 'WARNING',
  DANGER = 'DANGER',
}

export enum actionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  REMOVE = 'REMOVE',
  ADDED = 'ADDED',
}
