module.exports = {
  SELECTORS: {
    PEOPLE_TAB: 'button:contains("People")',
    DETAILS_TAB: 'button:contains("Details")',
    SUPPLIERS_TAB: 'button:contains("Suppliers")',
    NOTES_TAB: 'button:contains("Notes")',
    ACTIVITY_LOG_TAB: 'button:contains("Activity Log")',
    DETAILS_SECTION: {
      CHOOSEDOC_BTN: '[data-cy="choose-doc-input"]',
      UPLOADDOC_BTN: '[data-cy="upload-doc"]',
      MESSAGEDOC: '.css-1jbg0bd',
      FILEATTACHED: '[data-cy="project-attachment-container"]',
      DOWNLOADFILE_BTN: 'button:contains("Download")',
      DELETEICON_BTN: '[data-cy="project-attachment-deleteIcon"]',
      CHOOSEDOC: '[data-cy="choose-doc"]',
    },
    SUPPLIERS_SECTION: {
      DISCOVER_BTN: 'button:contains("Discover")',
    },
    PEOPLE_SECTION: {
      INVITEUSER: 'button:contains("Invite User")',
      //INVITE_BTN: '#chakra-modal--body-35 > :nth-child(3) > .chakra-button > .chakra-text',
      CLOSE: 'button[aria-label="Close"]',
      //ACCEPTAR_PROJECT:'button:contains("Accept")',
      //ALLPROJECT: 'button:contains("All Projects")',
      //LISTPROJECT:'button:contains("Test Automation")',
      //SEARCH: '.chakra-input__right-element > .chakra-button',
    },
    NOTES_SECTION: {
      WRITING_COMMENT: ':contains("Comment")+>textarea',
      SEND_BTN: 'button:contains("Send")',
      REPLY_BTN: 'img[src*="/note_reply"]',
      WRITING_COMMENTREPLY: ':contains("Reply")+>textarea',
      SENDREPLY_BTN: ':contains("Reply")++>button:contains("Send")',
      EDIT_BTN: 'img[src*="/note_edit"]',
      EDITCOMMENT: ':contains("Edit")+>textarea',
      SENDEDIT_BTN: ':contains("Edit") ++> button[id*="project-notes-form-submit-button"]',
      DELETE_ICON: 'button img[src*="/note_delete"]',
      DELETE_BTN: 'button:contains("Delete")',
      SPINNER: '.chakra-spinner',
    },
    ACTIVITY_LOG_SECTION: {
      LAST_ACTIVITY_LOG: '[id*="tabpanel"]:visible >> :nth-child(1)',
    },
    MENUPROJECT: '#popover-trigger-project-options-button-000',
    DELETEPROJECT: 'h4:contains("Delete Project")',
    CONFIRM_BTN: 'button:contains("Confirm")',
    SKELETON_ANIMATION: '.chakra-skeleton',
  },
  TEXTS: {},
};
