module.exports = {
  SELECTORS: {
    SEARCH: {
      SEARCH_BTN: 'button:contains("Search"):visible',
      COMPANIES_OPTIONS_BTN: '[aria-label="Companies Options"]',
      COMPANIES_OPTIONS_LIST: '[aria-label="Companies Options"]+>>button',
      SEARCH_COMPANY_TXTFLD: '.chakra-input',
    },
    COMPANIES_TABLE: 'table:contains("COMPANY NAME")',
    COMPANIES_TABLEROWS: 'table:contains("COMPANY NAME")>tbody>tr',
    MENU_BUTTON: '[data-cy="create-a-supplier-company-button"]',
    CREATEASUPPLIERCOPANY: '[data-cy="create-a-supplier-company"]',
    NAMEORTAXID_FIELD: '.chakra-input',
    CREATENEWCOMPANY_BTN: '.chakra-modal__footer > .chakra-button',
    COMPANYNAME_FIELD: '.chakra-stack > .chakra-input',
    TAXID_FIELD: ':contains("*Tax ID")>input[placeholder="US:00-0000000"]',
    CREATECOMPANY_BTN: '.chakra-modal__footer > .chakra-button',
    SAVECHANGES_BTN: '.css-k4fngg',
    FILTERS: 'button:contains("Filters")',
    BASIC: 'button:contains("Basic")',
    APPLYFILYERS: 'button:contains("Apply filters")',
    ADDTO: 'tbody [id*="popover-trigger"]',
    MOREPROJECTS: ':contains("Projects")+>:contains("More Projects")',
    TAGCOMPANY: 'h5:contains("Tags")+',
    OWNERSHIPCOMPANY: 'h5:contains("Ownership")+',
    TAXIDCOMPANY: 'h5:contains("Tax Identification Number")+',
    DESCRIPTIONCOMPANY: 'h5:contains("Description")+',
  },
  TEXTS: {},
};
