export const stimulusLocationsIndex = {
  fields: [
    {
      name: 'id',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: true,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'addressStreet',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'addressStreet2',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'addressStreet3',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'postalCode',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'country',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'city',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'state',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'location',
      type: 'Edm.GeographyPoint',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'companyId',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'tags',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'legalBusinessName',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'previousBusinessNames',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'otherBusinessNames',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'businessNames',
      type: 'Collection(Edm.ComplexType)',
      fields: [
        {
          name: 'name',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: 'standard.lucene',
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
      ],
    },
    {
      name: 'description',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'doingBusinessAs',
      type: 'Edm.String',
      searchable: true,
      filterable: false,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'displayName',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'scoreValue',
      type: 'Edm.Int32',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'diverseOwnership',
      type: 'Edm.String',
      searchable: true,
      filterable: false,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'typeOfLegalEntity',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'taxIdNo',
      type: 'Edm.String',
      searchable: true,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: 'standard.lucene',
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'revenue',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'revenueGrowthCAGR',
      type: 'Edm.String',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'netProfit',
      type: 'Edm.Double',
      searchable: false,
      filterable: false,
      retrievable: false,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'netProfitPct',
      type: 'Edm.String',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'totalAssets',
      type: 'Edm.String',
      searchable: false,
      filterable: false,
      retrievable: false,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'totalLiabilities',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'customers',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'facebookFollowers',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'twitterFollowers',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'linkedInFollowers',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'revenuePerEmployee',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'employeesTotal',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'leadershipTeamTotal',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: false,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'netPromoterScore',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'boardTotal',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: false,
      sortable: false,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'employeesTotalGrowthCAGR_double',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'assetsPctOfRevenue',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'liabilitiesPctOfRevenue',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'totalAssets_double',
      type: 'Edm.Double',
      searchable: false,
      filterable: true,
      retrievable: true,
      sortable: true,
      facetable: false,
      key: false,
      indexAnalyzer: null,
      searchAnalyzer: null,
      analyzer: null,
      normalizer: null,
      dimensions: null,
      vectorSearchConfiguration: null,
      synonymMaps: [],
    },
    {
      name: 'parentCompany',
      type: 'Collection(Edm.ComplexType)',
      fields: [
        {
          name: 'legalBusinessName',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: 'standard.lucene',
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
      ],
    },
    {
      name: 'tcr',
      type: 'Collection(Edm.ComplexType)',
      fields: [
        {
          name: 'id',
          type: 'Edm.String',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'status',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'type',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'created',
          type: 'Edm.DateTimeOffset',
          searchable: false,
          filterable: false,
          retrievable: false,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'updated',
          type: 'Edm.DateTimeOffset',
          searchable: false,
          filterable: false,
          retrievable: false,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'favoriteUpdatedAt',
          type: 'Edm.DateTimeOffset',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: true,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'companyId',
          type: 'Edm.String',
          searchable: false,
          filterable: false,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'tenantId',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'isFavorite',
          type: 'Edm.Boolean',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'isToCompare',
          type: 'Edm.Boolean',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'internalName',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: 'standard.lucene',
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
      ],
    },
    {
      name: 'contingencies',
      type: 'Collection(Edm.ComplexType)',
      fields: [
        {
          name: 'name',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
      ],
    },
    {
      name: 'products',
      type: 'Collection(Edm.ComplexType)',
      fields: [
        {
          name: 'name',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
      ],
    },
    {
      name: 'certifications',
      type: 'Collection(Edm.ComplexType)',
      fields: [
        {
          name: 'name',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
      ],
    },
    {
      name: 'insurances',
      type: 'Collection(Edm.ComplexType)',
      fields: [
        {
          name: 'name',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
      ],
    },
    {
      name: 'score',
      type: 'Edm.ComplexType',
      fields: [
        {
          name: 'brandValue',
          type: 'Edm.Double',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: true,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'customerValue',
          type: 'Edm.Double',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: true,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'employeeValue',
          type: 'Edm.Double',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: true,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'longevityValue',
          type: 'Edm.Double',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: true,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'scoreValue',
          type: 'Edm.Double',
          searchable: false,
          filterable: true,
          retrievable: true,
          sortable: true,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
      ],
    },
    {
      name: 'industries',
      type: 'Collection(Edm.ComplexType)',
      fields: [
        {
          name: 'code',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'description_index',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'title_index',
          type: 'Edm.String',
          searchable: true,
          filterable: true,
          retrievable: true,
          sortable: false,
          facetable: false,
          key: false,
          indexAnalyzer: null,
          searchAnalyzer: null,
          analyzer: null,
          normalizer: null,
          dimensions: null,
          vectorSearchConfiguration: null,
          synonymMaps: [],
        },
        {
          name: 'tenants',
          type: 'Collection(Edm.ComplexType)',
          fields: [
            {
              name: 'tenantId',
              type: 'Edm.String',
              searchable: true,
              filterable: true,
              retrievable: true,
              sortable: false,
              facetable: false,
              key: false,
              indexAnalyzer: null,
              searchAnalyzer: null,
              analyzer: null,
              normalizer: null,
              dimensions: null,
              vectorSearchConfiguration: null,
              synonymMaps: [],
            },
          ],
        },
      ],
    },
  ],
};
