export const findState = (input: string) => {
  const states = {
    'New York': 'NY',
    California: 'CA',
    Texas: 'TX',
    Florida: 'FL',
    Illinois: 'IL',
    Pennsylvania: 'PA',
    Ohio: 'OH',
    Georgia: 'GA',
    'North Carolina': 'NC',
    Michigan: 'MI',
    'New Jersey': 'NJ',
    Virginia: 'VA',
    Washington: 'WA',
    Arizona: 'AZ',
    Massachusetts: 'MA',
    Tennessee: 'TN',
    Indiana: 'IN',
    Missouri: 'MO',
    Maryland: 'MD',
    Wisconsin: 'WI',
    Colorado: 'CO',
    Minnesota: 'MN',
    'South Carolina': 'SC',
    Alabama: 'AL',
    Louisiana: 'LA',
    Kentucky: 'KY',
    Oregon: 'OR',
    Oklahoma: 'OK',
    Connecticut: 'CT',
    Iowa: 'IA',
    Utah: 'UT',
    Nevada: 'NV',
    Arkansas: 'AR',
    Mississippi: 'MS',
    Kansas: 'KS',
    'New Mexico': 'NM',
    Nebraska: 'NE',
    Idaho: 'ID',
    'West Virginia': 'WV',
    Hawaii: 'HI',
    'New Hampshire': 'NH',
    Maine: 'ME',
    Montana: 'MT',
    'Rhode Island': 'RI',
    Delaware: 'DE',
    'South Dakota': 'SD',
    'North Dakota': 'ND',
    Alaska: 'AK',
    Vermont: 'VT',
    Wyoming: 'WY',
  };
  return states[input] || Object.keys(states).find((key) => states[key] === input) || '';
};
